# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Metrics
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: baderouaich
          template: classic
          base: header, activity, community, repositories
          config_timezone: Africa/Casablanca

          plugin_followup: yes
          plugin_followup_archived: yes
          plugin_followup_sections: repositories

          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: programming #, markup
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 2% # hide languages with less than X%

          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_types: commit, pull_request, issues

          # # https://github.com/lowlighter/metrics/blob/master/source/plugins/code/README.md
          # plugin_code: yes
          # plugin_code_visibility: public # only get snippets from my public repos (DON'T REVEAL ANY PRIVATE REPOS CONTENTS)
          # plugin_code_lines: 12
          # plugin_code_days: 365 # get snippets from last N days activity, default 3
          # plugin_code_languages: c++, c, dart
          # plugin_code_load: 1000

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/traffic/README.md
          plugin_traffic: yes

          # https://github.com/lowlighter/metrics/blob/master/source/plugins/habits/README.md
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_facts: yes
          plugin_habits_charts: no