# Visit https://github.com/lowlighter/metrics#-documentation for full reference
name: Snippet of the day
on:
  # Schedule updates (each hour)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
        filename: metrics.plugin.code.svg
        token: ${{ secrets.METRICS_TOKEN }}
        base: ""
        plugin_code: yes
        plugin_code_languages: c++, c, dart
        plugin_code_load: 400